// frontend/src/components/Layout.vue
<template>
  <div class="min-h-screen bg-slate-100 dark:bg-slate-900">
    <header class="bg-white dark:bg-slate-800 shadow-sm border-b border-slate-200 dark:border-slate-700">
      <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div class="flex justify-between h-16 items-center">
          <h1 class="text-xl font-bold text-slate-900 dark:text-white">ProxyPool</h1>
          <button
            @click="appStore.toggleDarkMode"
            class="px-3 py-2 rounded-lg bg-slate-200 dark:bg-slate-700 text-slate-700 dark:text-slate-200"
          >
            {{ appStore.darkMode ? '浅色' : '深色' }}
          </button>
        </div>
      </div>
    </header>

    <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-6">
      <nav class="mb-6 flex gap-2 flex-wrap">
        <router-link
          v-for="item in navItems"
          :key="item.path"
          :to="item.path"
          class="px-4 py-2 rounded-lg font-medium transition-colors"
          :class="$route.path === item.path
            ? 'bg-blue-500 text-white'
            : 'bg-white dark:bg-slate-800 text-slate-700 dark:text-slate-200 hover:bg-slate-100 dark:hover:bg-slate-700'"
        >
          {{ item.label }}
        </router-link>
      </nav>

      <main>
        <slot />
      </main>
    </div>

    <Toast />
  </div>
</template>

<script setup lang="ts">
import { useAppStore } from '@/stores/appStore';
import Toast from './Toast.vue';

const appStore = useAppStore();

const navItems = [
  { path: '/dashboard', label: '仪表盘' },
  { path: '/proxies', label: '代理列表' },
  { path: '/sources', label: '来源管理' },
  { path: '/settings', label: '系统设置' }
];
</script>

// src/renderer/components/Layout.tsx
import { useState } from 'react';
import { useTheme } from '../contexts/ThemeContext';
import ProxyList from './ProxyList';
import Dashboard from './Dashboard';
import SourceList from './SourceList';
import Settings from './Settings';
import Toast from './Toast';

type Tab = 'dashboard' | 'proxies' | 'sources' | 'settings';

const TABS: { id: Tab; label: string }[] = [
  { id: 'dashboard', label: '仪表板' },
  { id: 'proxies', label: '代理列表' },
  { id: 'sources', label: '代理来源' },
  { id: 'settings', label: '设置' },
];

export default function Layout() {
  const { theme, toggleTheme } = useTheme();
  const [activeTab, setActiveTab] = useState<Tab>('dashboard');
  const [mobileMenuOpen, setMobileMenuOpen] = useState(false);

  const handleTabChange = (tab: Tab) => {
    setActiveTab(tab);
    setMobileMenuOpen(false);
  };

  return (
    <div className="min-h-screen bg-slate-50 dark:bg-slate-900">
      {/* 顶部导航栏 */}
      <nav className="fixed top-4 left-4 right-4 z-50 animate-slide-up">
        <div className="max-w-7xl mx-auto bg-white/90 dark:bg-slate-800/90 backdrop-blur-md shadow-lg rounded-2xl border border-slate-200 dark:border-slate-700">
          <div className="px-6">
            <div className="flex justify-between h-16">
              <div className="flex items-center space-x-8">
                {/* Logo */}
                <div className="flex-shrink-0 flex items-center">
                  <div className="w-8 h-8 bg-gradient-to-br from-green-400 to-green-600 rounded-lg flex items-center justify-center">
                    <svg className="w-5 h-5 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M21 12a9 9 0 01-9 9m9-9a9 9 0 00-9-9m9 9H3m9 9a9 9 0 01-9-9m9 9c1.657 0 3-4.03 3-9s-1.343-9-3-9m0 18c-1.657 0-3-4.03-3-9s1.343-9 3-9m-9 9a9 9 0 019-9" />
                    </svg>
                  </div>
                  <h1 className="ml-3 text-lg font-bold text-slate-900 dark:text-white font-mono">IP代理池</h1>
                </div>

                {/* 桌面端导航标签 */}
                <div className="hidden md:flex space-x-1">
                  {TABS.map((tab) => (
                    <button
                      key={tab.id}
                      onClick={() => handleTabChange(tab.id)}
                      className={`px-4 py-2 rounded-lg text-sm font-medium transition-all duration-200 cursor-pointer ${
                        activeTab === tab.id
                          ? 'bg-green-500 text-white shadow-md'
                          : 'text-slate-600 dark:text-slate-300 hover:bg-slate-100 dark:hover:bg-slate-700'
                      }`}
                    >
                      {tab.label}
                    </button>
                  ))}
                </div>
              </div>

              <div className="flex items-center space-x-2">
                {/* 主题切换 */}
                <button
                  onClick={toggleTheme}
                  className="p-2 rounded-lg text-slate-600 dark:text-slate-300 hover:bg-slate-100 dark:hover:bg-slate-700 transition-colors duration-200 cursor-pointer"
                  aria-label="切换主题"
                >
                  {theme === 'light' ? (
                    <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M20.354 15.354A9 9 0 018.646 3.646 9.003 9.003 0 0012 21a9.003 9.003 0 008.354-5.646z" />
                    </svg>
                  ) : (
                    <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 3v1m0 16v1m9-9h-1M4 12H3m15.364 6.364l-.707-.707M6.343 6.343l-.707-.707m12.728 0l-.707.707M6.343 17.657l-.707.707M16 12a4 4 0 11-8 0 4 4 0 018 0z" />
                    </svg>
                  )}
                </button>

                {/* 移动端汉堡菜单按钮 */}
                <button
                  onClick={() => setMobileMenuOpen(!mobileMenuOpen)}
                  className="md:hidden p-2 rounded-lg text-slate-600 dark:text-slate-300 hover:bg-slate-100 dark:hover:bg-slate-700 transition-colors duration-200 cursor-pointer"
                  aria-label="打开菜单"
                >
                  {mobileMenuOpen ? (
                    <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
                    </svg>
                  ) : (
                    <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 6h16M4 12h16M4 18h16" />
                    </svg>
                  )}
                </button>
              </div>
            </div>
          </div>

          {/* 移动端下拉菜单 */}
          {mobileMenuOpen && (
            <div className="md:hidden border-t border-slate-200 dark:border-slate-700 px-4 py-3 space-y-1">
              {TABS.map((tab) => (
                <button
                  key={tab.id}
                  onClick={() => handleTabChange(tab.id)}
                  className={`w-full text-left px-4 py-3 rounded-lg text-sm font-medium transition-all duration-200 cursor-pointer ${
                    activeTab === tab.id
                      ? 'bg-green-500 text-white'
                      : 'text-slate-600 dark:text-slate-300 hover:bg-slate-100 dark:hover:bg-slate-700'
                  }`}
                >
                  {tab.label}
                </button>
              ))}
            </div>
          )}
        </div>
      </nav>

      {/* 主内容区 */}
      <main className="max-w-7xl mx-auto pt-24 pb-8 px-4 sm:px-6 lg:px-8">
        <div className="animate-fade-in">
          {activeTab === 'dashboard' && <Dashboard />}
          {activeTab === 'proxies' && <ProxyList />}
          {activeTab === 'sources' && <SourceList />}
          {activeTab === 'settings' && <Settings />}
        </div>
      </main>

      {/* Toast通知 */}
      <Toast />
    </div>
  );
}
